name = "gazelle-api"
main = "src/index.ts"
compatibility_date = "2025-10-14"
compatibility_flags = ["nodejs_compat"]

# Workers Logs
[observability]
enabled = true

# D1 Database Binding
[[d1_databases]]
binding = "DB"
database_name = "gazelle-db"
database_id = "65760f23-09ec-4c47-8dec-c94d193ce71d"

# KV Namespace Bindings
[[kv_namespaces]]
binding = "SESSIONS"
id = "1c464ee9f52a4855aeab8cd4b083a0f2"

[[kv_namespaces]]
binding = "CACHE"
id = "3a4495192e254661bc4fbce10e0f381d"

# Environment Variables
# Secrets (set via wrangler secret put): CLAUDE_API_KEY, PRIVY_APP_SECRET
# Public vars (safe to commit):
[vars]
PRIVY_APP_ID = "cmgr1bec602lvkz0c2tobm0sz"
MAPBOX_TOKEN = "pk.eyJ1IjoiZGFmaXNoZXIyMDAwIiwiYSI6ImNtZ3IxN2UwdzE2NTIybHE0YXlndmg4d2kifQ._PaGsU2QYoxEzESAKm3LsQ"
